{{- if .Values.ingress.enabled -}}
{{- $fullName := include "ingress-demo.fullname" . -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    app.kubernetes.io/name: {{ include "ingress-demo.name" . }}
    helm.sh/chart: {{ include "ingress-demo.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range $host := .Values.ingress.hosts }}
    - http:
        paths:
    {{- range $item := $host.paths }}
          - path: {{ $item.path }}
            backend:
              serviceName: {{ .serviceName }}
              servicePort: {{ .servicePort }}
    {{- end }}
  {{- end }}
{{- end }}
